### ISSUE TITLE
Can SizeManager add item position?

### ISSUE THREAD

**Issue by kjsolo** [Fondesa/RecyclerViewDivider#20]
```kotlin
object : SizeManager {
    override fun itemSize(drawable: Drawable, orientation: Int, groupCount: Int, groupIndex: Int): Int {
        // I want to know which item is
    }
}
```

**Comment by Fondesa** [comment]
It could be a good idea to know which item is, but it's not that simple.
Because the size must be equal for all the items in a group.
So, adding the parameter `itemPosition` could bring to a misunderstanding of this method.

For those motivations, I don't think I'll expose the position of the item.
If you have a better solution, feel free to tell it.
